name: movie_explorer
description: "A Movie Explorer Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # HTTP requests
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Environment variables
  flutter_dotenv: ^5.2.1

  # Image handling
  cached_network_image: ^3.4.1

  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

assets:
  - assets/