name: movie_explorer
description: "A Movie Explorer Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # HTTP requests
  dio: ^5.1.1
  pretty_dio_logger: ^1.1.1

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Image handling
  cached_network_image: ^3.2.3

  # For smooth scrolling
  infinite_scroll_pagination: ^4.1.0

  # Icons
  font_awesome_flutter: ^10.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
